# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: datawarehouse.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'datawarehouse.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13\x64\x61tawarehouse.proto\"\x1c\n\x0cHelloRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"\x1d\n\nHelloReply\x12\x0f\n\x07message\x18\x01 \x01(\t\"@\n\x0fWarehouseRecord\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0f\n\x07product\x18\x02 \x01(\t\x12\x10\n\x08quantity\x18\x03 \x01(\x05\" \n\x0eWarehouseReply\x12\x0e\n\x06status\x18\x01 \x01(\t2p\n\x14\x44\x61taWarehouseService\x12&\n\x08SayHello\x12\r.HelloRequest\x1a\x0b.HelloReply\x12\x30\n\x0bStoreRecord\x12\x10.WarehouseRecord\x1a\x0f.WarehouseReplyB\x0f\n\x0b\x64\x65zsys.grpcP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'datawarehouse_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\013dezsys.grpcP\001'
  _globals['_HELLOREQUEST']._serialized_start=23
  _globals['_HELLOREQUEST']._serialized_end=51
  _globals['_HELLOREPLY']._serialized_start=53
  _globals['_HELLOREPLY']._serialized_end=82
  _globals['_WAREHOUSERECORD']._serialized_start=84
  _globals['_WAREHOUSERECORD']._serialized_end=148
  _globals['_WAREHOUSEREPLY']._serialized_start=150
  _globals['_WAREHOUSEREPLY']._serialized_end=182
  _globals['_DATAWAREHOUSESERVICE']._serialized_start=184
  _globals['_DATAWAREHOUSESERVICE']._serialized_end=296
# @@protoc_insertion_point(module_scope)
